CREATE TABLE IF NOT EXISTS currency
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency VARCHAR(10)                              NOT NULL,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

ALTER TABLE currency
    ADD CONSTRAINT uc_currency_currency UNIQUE (currency);
